### ISSUE TITLE
Stumped after "Open Implemented Design"

### ISSUE THREAD

**Issue by tommythorn** [tomverbeure/kv260_bringup#1]
Tom, thanks a million for this guide.  Not being used to Xilinx' tools (and MPSoC in particular), this is really awesome.  I mostly managed to follow the steps verbatim (some variation could be because I opted to update to 2021.1.1).

Unfortunately after step "Open Implemented Design" I ended up here which doesn't have the "Design Constraints" tab.  Did I miss something or is there a step missing?

<img width="1509" alt="Screen Shot 2021-08-16 at 00 09 16" src="https://user-images.githubusercontent.com/862616/129525078-1b0701f4-4670-4253-8b8b-bdc6352873a7.png">

**Comment by tomverbeure** [comment]
I haven’t looked at it since writing this up. But let me retry sometime tomorrow.

**Comment by tommythorn** [comment]
I don’t know if you would be up for recording the screen (no audio required)?

**Comment by tomverbeure** [comment]
I went through my whole recipe again (good that I wrote it down!).

After "Open Implemented Design", you need to edit the I/O Port.  You can enable the "I/O Ports" tab via the menu bar: Window -> I/O Ports.

Tom

**Comment by tommythorn** [comment]
Brilliant, with this I made it to the end, toggling the fan.  Thanks.

FWIW, it wasn't clear to me what you meant my "Install PetaLinux", but Xilinx's "Getting started" instructions already had me load the SDcard, and that appeared sufficient.
